<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AIITSM.Infrastructure\AIITSM.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\01_M1_IdentityAccess\" />
    <Folder Include="Controllers\02_M2_IncidentManagement\" />
    <Folder Include="Controllers\03_M3_AgentWorkflow\" />
    <Folder Include="Controllers\04_M4_Administration\" />
    <Folder Include="Controllers\05_M5_Reporting\" />
    <Folder Include="Controllers\07_M7_Automation\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
  </ItemGroup>

</Project>
